/**
 * Turns public/my-resume.pdf into src/lib/resume.js, the assistant's only
 * source of truth about Raiyan.
 *
 *   node scripts/extract-resume.mjs
 *
 * Extracted ahead of time rather than parsed per request: the text never
 * changes between deploys, PDF parsing is slow, and — most importantly — the
 * generated file is plain text you can read and correct. If the assistant
 * answers something wrong, fix it there.
 */

import fs from "node:fs";
import path from "node:path";

// pdfjs reaches for browser globals it never actually uses for text extraction.
class MatrixStub {
  constructor() {
    Object.assign(this, { a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 });
  }
  scale() {
    return this;
  }
  translate() {
    return this;
  }
  multiply() {
    return this;
  }
  inverse() {
    return this;
  }
}

globalThis.DOMMatrix ??= MatrixStub;
globalThis.ImageData ??= class {};
globalThis.Path2D ??= class {};

const root = path.join(import.meta.dirname, "..");
const source = path.join(root, "public", "my-resume.pdf");
const target = path.join(root, "src", "lib", "resume.js");

const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");

const doc = await pdfjs.getDocument({
  data: new Uint8Array(fs.readFileSync(source)),
  useSystemFonts: false,
  disableFontFace: true,
}).promise;

const lines = [];

for (let page = 1; page <= doc.numPages; page += 1) {
  const content = await (await doc.getPage(page)).getTextContent();

  // Group glyph runs onto shared baselines, then order each line left to right.
  const rows = new Map();
  for (const item of content.items) {
    if (!item.str?.trim()) continue;
    const y = Math.round(item.transform[5]);
    if (!rows.has(y)) rows.set(y, []);
    rows.get(y).push(item);
  }

  for (const [, row] of [...rows.entries()].sort((a, b) => b[0] - a[0])) {
    row.sort((a, b) => a.transform[4] - b.transform[4]);
    const text = row
      .map((item) => item.str)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    if (text) lines.push(text);
  }
}

const resume = lines.join("\n");

fs.writeFileSync(
  target,
  `// Generated by scripts/extract-resume.mjs from public/my-resume.pdf.\n` +
    `// Safe to edit by hand — regenerating overwrites it, so re-apply any\n` +
    `// corrections in the PDF itself.\n` +
    `export const RESUME = ${JSON.stringify(resume)};\n`,
  "utf8",
);

console.log(`${doc.numPages} pages, ${lines.length} lines, ${resume.length} chars`);
console.log(`wrote ${path.relative(root, target)}`);
